# Generated by Django 2.2.2 on 2019-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_type_code', models.CharField(max_length=100)),
                ('Room_code', models.CharField(max_length=100)),
                ('type_name', models.TextField(max_length=100)),
                ('capacity', models.TextField(max_length=100)),
                ('Availible', models.BooleanField(default=True)),
            ],
        ),
    ]
