# Generated by Django 2.2.2 on 2019-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190721_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtypecode',
            field=models.IntegerField(),
        ),
    ]
