# Generated by Django 2.2.2 on 2019-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20190721_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomtypecode',
            field=models.CharField(max_length=100),
        ),
    ]
