# Generated by Django 2.2.2 on 2019-07-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190721_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head_name', models.CharField(max_length=100)),
                ('No_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('extra_bed', models.BooleanField(default=False)),
                ('Identity_no', models.CharField(max_length=100)),
                ('Room_code', models.CharField(max_length=100)),
                ('No_of_nights', models.IntegerField()),
            ],
        ),
    ]
