# Generated by Django 2.2.2 on 2019-07-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='extra_bed',
        ),
    ]
