# Generated by Django 2.2.2 on 2019-07-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_guest_extra_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='No_of_adults',
            field=models.IntegerField(default=0),
        ),
    ]
