# Generated by Django 2.2.2 on 2019-07-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20190723_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='No_of_nights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='no_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
