# Generated by Django 2.2.2 on 2019-07-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20190723_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='No_of_adults',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='No_of_nights',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='no_of_children',
            field=models.CharField(max_length=100),
        ),
    ]
