# Generated by Django 2.2.2 on 2019-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_rooms_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='Timeofbooking',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='checkindate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
