# Generated by Django 2.2.2 on 2019-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_auto_20190723_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='checkindate',
        ),
    ]
