# Generated by Django 2.2.2 on 2019-07-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_remove_guest_checkindate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Timeofbooking',
            new_name='time',
        ),
    ]
