# Generated by Django 2.2.2 on 2019-07-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20190724_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='time',
        ),
    ]
