# Generated by Django 2.2.2 on 2019-07-23 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_remove_guest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
