# Generated by Django 2.2.2 on 2019-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_remove_guest_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomcode',
            field=models.IntegerField(max_length=100),
        ),
    ]
