# Generated by Django 2.2.2 on 2019-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_auto_20190724_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Roomcode',
            field=models.IntegerField(),
        ),
    ]
